name: Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: Whether or not this is a prerelease
        type: boolean
        default: false
        required: true
#  push:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: './'
          fetch-depth: 0
      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: dependencies
        run: ./gradlew --no-daemon dependencies
      - name: Release to github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.M2_USER }}
          PASSWORD: ${{ secrets.M2_PASS }}
          # just use master
          RELEASE_TARGET: master
        run: ./gradlew --no-daemon build publish githubRelease -x test
